# https://taskfile.org

version: '2'

tasks:
  update-mdb:
    cmds:
      - "git subtree pull --prefix backends/postgres/messagedb https://github.com/message-db/message-db.git master --squash"
  dev:
    cmds:
      - docker-compose up -d
  dev-down:
    cmds:
      - docker-compose down